import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import fontkit from '@pdf-lib/fontkit'
import { sha256 } from './crypto'

let _koreanFontBytes: Buffer | null = null
async function getKoreanFont(): Promise<Buffer> {
  if (!_koreanFontBytes) {
    const storage = useStorage('assets:fonts')
    const data = await storage.getItemRaw('NotoSansKR-Regular.ttf')
    _koreanFontBytes = Buffer.from(data as ArrayBuffer)
  }
  return _koreanFontBytes
}

/** Compute SHA-256 hash of a PDF buffer */
export function hashPdf(pdfBuffer: Buffer): string {
  return sha256(pdfBuffer)
}

/** Embed a signature image into a PDF at specified coordinates */
export async function embedSignatureInPdf(
  pdfBuffer: Buffer,
  signatureImage: Buffer,
  page: number,
  x: number,
  y: number,
  width: number,
  height: number,
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.load(pdfBuffer)
  const pdfPage = pdfDoc.getPage(page)

  // Detect image type and embed accordingly
  let image
  const header = signatureImage.slice(0, 4).toString('hex')
  if (header.startsWith('89504e47')) {
    image = await pdfDoc.embedPng(signatureImage)
  } else {
    image = await pdfDoc.embedJpg(signatureImage)
  }

  pdfPage.drawImage(image, { x, y, width, height })

  const modifiedPdf = await pdfDoc.save()
  return Buffer.from(modifiedPdf)
}

/** Add text field value to PDF */
export async function addTextToPdf(
  pdfBuffer: Buffer,
  text: string,
  page: number,
  x: number,
  y: number,
  fontSize: number = 12,
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.load(pdfBuffer)
  const pdfPage = pdfDoc.getPage(page)
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)

  pdfPage.drawText(text, {
    x,
    y,
    size: fontSize,
    font,
    color: rgb(0, 0, 0),
  })

  const modifiedPdf = await pdfDoc.save()
  return Buffer.from(modifiedPdf)
}

/** Generate audit trail certificate PDF */
export async function generateAuditTrailPdf(auditData: {
  documentTitle: string
  documentHash: string
  events: Array<{
    eventType: string
    actorName: string
    timestamp: string
    ipAddress?: string
    details?: string
  }>
}): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create()
  pdfDoc.registerFontkit(fontkit)

  const page = pdfDoc.addPage([595, 842]) // A4
  const koreanFont = await pdfDoc.embedFont(await getKoreanFont())
  const font = koreanFont
  const boldFont = koreanFont

  let y = 780

  // Header
  page.drawText('Audit Trail Certificate', {
    x: 50, y, size: 20, font: boldFont, color: rgb(0.15, 0.39, 0.93),
  })
  y -= 30

  page.drawText('Pactery Electronic Signature Service', {
    x: 50, y, size: 10, font, color: rgb(0.5, 0.5, 0.5),
  })
  y -= 30

  // Document info
  page.drawText(`Document: ${auditData.documentTitle}`, {
    x: 50, y, size: 12, font: boldFont,
  })
  y -= 20

  page.drawText(`SHA-256: ${auditData.documentHash}`, {
    x: 50, y, size: 8, font, color: rgb(0.3, 0.3, 0.3),
  })
  y -= 30

  // Separator
  page.drawLine({
    start: { x: 50, y }, end: { x: 545, y },
    thickness: 1, color: rgb(0.8, 0.8, 0.8),
  })
  y -= 20

  // Events
  for (const event of auditData.events) {
    if (y < 60) break // page overflow guard

    page.drawText(`[${event.timestamp}]`, {
      x: 50, y, size: 9, font, color: rgb(0.4, 0.4, 0.4),
    })
    y -= 15

    page.drawText(`${event.eventType}: ${event.actorName}`, {
      x: 70, y, size: 10, font: boldFont,
    })
    y -= 15

    if (event.ipAddress) {
      page.drawText(`IP: ${event.ipAddress}`, {
        x: 70, y, size: 8, font, color: rgb(0.5, 0.5, 0.5),
      })
      y -= 12
    }

    if (event.details) {
      page.drawText(event.details, {
        x: 70, y, size: 8, font, color: rgb(0.5, 0.5, 0.5),
      })
      y -= 12
    }

    y -= 10
  }

  // Footer
  page.drawText(`Generated by Pactery - ${new Date().toISOString()}`, {
    x: 50, y: 30, size: 8, font, color: rgb(0.6, 0.6, 0.6),
  })

  const pdfBytes = await pdfDoc.save()
  return Buffer.from(pdfBytes)
}
